# Generated by Django 3.0.7 on 2022-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220730_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended_song',
            name='recommendation_liked',
            field=models.BooleanField(null=True),
        ),
    ]
